import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    console.log('layout')
    return (
        <html lang="en">
        <body className={inter.className}>
        <nav>
            <Link href="/">首页</Link>
            <Link href="/about">About</Link>
            <Link href="/more">More</Link>
        </nav>
        <main>
            {children}
        </main>
        </body>
        </html>
    )
}
